services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole                                      # Set the hostname for pihole
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata                                   # Set your timezone
      - FTLCONF_webserver_api_password=<YOUR_PASSWORD>    # Set the web interface password
      - DNS1=<<YOUR_UNBOUND_STATIC_IP>#5335               # Primary DNS server (Unbound)
      - DNS2=1.1.1.1                                      # Secondary DNS server (Cloudflare)
    volumes:
      - './etc-pihole/:/etc/pihole/'                      # Persistent Pi-hole data
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'                # Persistent DNSMasq data
    networks:
      pihole_macvlan:
        ipv4_address: <YOUR_IP>                           # Pick your desired IP
    cap_add:
      - NET_ADMIN                                         # Allow network administration
      - SYS_TIME                                          # Allow time adjustments

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    networks:
      pihole_macvlan:
        ipv4_address: <YOUR_UNBOUND_STATIC_IP>            # Pick your desired IP  
    expose:
      - "53"
      - "5335"

networks:
  pihole_macvlan:
    external: true
